FROM python:3.10
RUN python -m pip install --upgrade pip
RUN python --version && pip --version

ENV PYTHONUNBUFFERED 1

RUN mkdir saasot-app
WORKDIR saasot-app

ADD . /saasot-app
#RUN addgroup -S adifect-app && adduser -S adifect-app -G adifect-app
RUN pip install --no-cache-dir -r requirements.txt && \
        pip install gunicorn
        

RUN python manage.py collectstatic --no-input

# Copy the Nginx configuration file into the container
# COPY nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf

# Expose ports 80 and 443
# Copy SSL/TLS certificates and key to Nginx's SSL directory


# EXPOSE 443


RUN chmod +x gunicorn.sh
EXPOSE 8000
ENTRYPOINT ["./gunicorn.sh"]
#this is new one.

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]





